### ISSUE TITLE
Mods with BA2 files break mod deployment

### ISSUE THREAD

**Issue by scrubborn** [lVlyke/starfield-mod-loader#16]
If my mod im trying to install contains a BA2 file, then the app will infinitely repeat activating and deactivating the profile, requiring me to close and reopen it. I've seen this on multiple mods with BA2's.  
  
Edit - it appears to only happen if there are multiple ba2's in the mod? The "Laredo M2 .45acp Pistol" from nexus is one of the culprits for me.

**Comment by lVlyke** [comment]
Thanks for the bug report. I've tried several mods with BA2 archives including the one you mentioned, but I haven't been able to reproduce the issue so far. Are there any errors logged to the app.log file when this occurs?

**Comment by Boot152** [comment]
i think this is the same problem. It stops working sometimes and gets stuck deploying the mods. You have to manually delete the mods in the data folder for it to work again also it deletes the plugins.txt file.

[2025-01-12 06:11:40.155] [info]  Deploying profile Fall
[2025-01-12 06:11:40.169] [error] Mod deployment failed:  Error: Source and destination must not be the same.
    at Object.checkPathsSync (/home/user/Mods/resources/app/node_modules/fs-extra/lib/util/stat.js:75:13)
    at Object.moveSync (/home/user/Mods/resources/app/node_modules/fs-extra/lib/move/move-sync.js:14:52)
    at ElectronLoader.deployMods (/home/user/Mods/resources/app/electron.js:2035:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ElectronLoader.deployProfile (/home/user/Mods/resources/app/electron.js:2165:38)
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:86077)

**Comment by lVlyke** [comment]
> i think this is the same problem. It stops working sometimes and gets stuck deploying the mods. You have to manually delete the mods in the data folder for it to work again also it deletes the plugins.txt file.
> 
> [2025-01-12 06:11:40.155] [info] Deploying profile Fall [2025-01-12 06:11:40.169] [error] Mod deployment failed: Error: Source and destination must not be the same. at Object.checkPathsSync (/home/user/Mods/resources/app/node_modules/fs-extra/lib/util/stat.js:75:13) at Object.moveSync (/home/user/Mods/resources/app/node_modules/fs-extra/lib/move/move-sync.js:14:52) at ElectronLoader.deployMods (/home/user/Mods/resources/app/electron.js:2035:32) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async ElectronLoader.deployProfile (/home/user/Mods/resources/app/electron.js:2165:38) at async WebContents. (node:electron/js2c/browser_init:2:86077)

Interesting, it looks like the error occurs when backing up existing files, though I'm not sure what circumstances would cause the file and the backup location to be the same, as that shouldn't normally be possible. Hard to say if this is the same issue as the OP.

A new version has just been released that adds some additional logic to the backup process during deployment. I'm not sure if this will fix the issue but it may shed more light on what's causing it.

**Comment by Boot152** [comment]
I tried the new update It says this (Error] cancel Mod deployment failed: Error: Source and destination must not be the same.) and in the logs it gives ([warn]  (electron) 'session.getPreloads' is deprecated and will be removed. Please use 'session.getPreloadScripts' instead.) hope this help.
