### ISSUE TITLE
Mod deployment failed. Check app.log file for more information. 

### ISSUE THREAD

**Issue by Bootx5** [lVlyke/starfield-mod-loader#9]
Log says this
[2024-03-07 23:49:31.504] [error] Error: ENOENT: no such file or directory, open 'settings.json'
    at Object.openSync (node:fs:603:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:2131)
    at Object.readFileSync (node:fs:471:35)
    at Object.readFileSync (node:electron/js2c/asar_bundle:2:9462)
    at ElectronLoader.loadSettings (/home/user/Mods/resources/app/electron.js:577:32)
    at /home/user/Mods/resources/app/electron.js:152:29
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88656)
    at WebContents.emit (node:events:514:28)

Also what do I put in Plugin List Path?

**Comment by Bootx5** [comment]
I figured it out...
